
name: Run Telegram Userbot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Har 1 ghante me auto-run
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install Dependencies
  run: pip install -r requirements.txt

       
          

           - name: Start Userbot
      run: python userbot.py
      

            
    

